### ISSUE TITLE
Experiment Setup Failure on Macbook

### ISSUE THREAD

**Issue by SpaceRangerWes** [Azure/MachineLearningSamples-DeepLearningforPredictiveMaintenance#3]
When trying to setup the experiment locally on a mac using `az ml experiment prepare --target docker --run-configuration docker --debug` as stated in the README.md, I received the following error. My best assumption is some incompatible dependencies were included? 

```
Running: ['docker', 'build', '-f', '/tmp/azureml_runs/DLMacTest_1516927326357/azureml-setup/Dockerfile', '-t', 'azureml_ecbbada0d1338909d3a9d2816473e49b', '.']
Sending build context to Docker daemon  2.476MB
Step 1/14 : FROM microsoft/mmlspark:plus-0.7.9
 ---> fbfcd676ba2f
Step 2/14 : USER root
 ---> Using cache
 ---> b4b7b292b919
Step 3/14 : RUN mkdir -p $HOME/.cache
 ---> Using cache
 ---> 52a7e84bce2c
Step 4/14 : WORKDIR /
 ---> Using cache
 ---> 4d1b5e105165
Step 5/14 : COPY azureml-setup/99brokenproxy /etc/apt/apt.conf.d/
 ---> Using cache
 ---> aa458f09efdb
Step 6/14 : RUN if dpkg --compare-versions `conda --version | grep -oE '[^ ]+$'` lt 4.4.0; then conda update conda -c conda-canary; fi
 ---> Using cache
 ---> eebee044be56
Step 7/14 : COPY azureml-setup/mutated_conda_dependencies.yml azureml-setup/mutated_conda_dependencies.yml
 ---> Using cache
 ---> 59d7f6d22cfc
Step 8/14 : RUN conda env create -f azureml-setup/mutated_conda_dependencies.yml
 ---> Using cache
 ---> d1d430cd7435
Step 9/14 : ENV PATH $CONDA_HOME/envs/azureml_68770a78222484481995562c21f7d1d3/bin:$PATH
 ---> Using cache
 ---> 3f60268df6ce
Step 10/14 : COPY azureml-setup/spark_cache.py .
 ---> Using cache
 ---> 023fb1200c42
Step 11/14 : RUN $SPARK_HOME/bin/spark-submit "--repositories" "https://mmlspark.azureedge.net/maven,https://azuremldownloads.blob.core.windows.net/repo5qh91kdjs6" "--packages" "com.microsoft.ml.spark:mmlspark_2.11:0.7.9,com.microsoft.sqlserver:mssql-jdbc:6.2.1.jre8,com.microsoft:dprep_2.11:0.15" "--conf" "spark.app.name=Azure ML Experiment" "--conf" "spark.driver.memory=6g" "--conf" "spark.executor.memory=6g" "--conf" "spark.yarn.maxAppAttempts=1" "--driver-java-options" "-Dlog4j.configuration=file:./azureml-setup/log4j.properties" "--conf" "spark.eventLog.enabled=true" "--conf" "spark.eventLog.dir=./azureml-logs" spark_cache.py
 ---> Running in 32d16250dd0b

Exception in thread "main" java.lang.NoClassDefFoundError: org/spark_project/guava/cache/CacheLoader
	at org.apache.spark.deploy.SparkSubmitArguments.handleUnknown(SparkSubmitArguments.scala:460)
	at org.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:178)
	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:98)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.spark_project.guava.cache.CacheLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

The command '/bin/sh -c $SPARK_HOME/bin/spark-submit "--repositories" "https://mmlspark.azureedge.net/maven,https://azuremldownloads.blob.core.windows.net/repo5qh91kdjs6" "--packages" "com.microsoft.ml.spark:mmlspark_2.11:0.7.9,com.microsoft.sqlserver:mssql-jdbc:6.2.1.jre8,com.microsoft:dprep_2.11:0.15" "--conf" "spark.app.name=Azure ML Experiment" "--conf" "spark.driver.memory=6g" "--conf" "spark.executor.memory=6g" "--conf" "spark.yarn.maxAppAttempts=1" "--driver-java-options" "-Dlog4j.configuration=file:./azureml-setup/log4j.properties" "--conf" "spark.eventLog.enabled=true" "--conf" "spark.eventLog.dir=./azureml-logs" spark_cache.py' returned a non-zero code: 1



Command '['docker', 'build', '-f', '/tmp/azureml_runs/DLMacTest_1516927326357/azureml-setup/Dockerfile', '-t', 'azureml_ecbbada0d1338909d3a9d2816473e49b', '.']' returned non-zero exit status 1
Uploading experiment status to history service.
Adding run profile attachment control_log

Logging experiment failure in history service.
```

**Comment by ehrlinger** [comment]
I've just updated the mmlspark package reference to the latest version (0.9.9) in the lastest PR, so this may now work on your mac. Can you verify this by creating a new project from the template, and retrying to prepare the docker container?

**Comment by SpaceRangerWes** [comment]
I did the same thing last evening and can verify that it did correct the issue. Thank you John

**Comment by ehrlinger** [comment]
Huzzah!

**Comment by SpaceRangerWes** [comment]
So unfortunately I was mistaken. I created a PR with the solution I found, but the real solution may be to fix the dependency code instead of just changing the version in this sample. Sorry I got any hopes up, @ehrlinger :(

```
Step 11/14 : RUN $SPARK_HOME/bin/spark-submit "--repositories" "https://mmlspark.azureedge.net/maven,https://azuremldownloads.blob.core.windows.net/repo5qh91kdjs6,https://azuremldownloads.blob.core.windows.net/repo5qh91kdjs6" "--packages" "com.microsoft.ml.spark:mmlspark_2.11:0.9.9,com.microsoft:dprep_2.11:0.15,com.microsoft.sqlserver:mssql-jdbc:6.2.1.jre8,com.microsoft:dprep_2.11:0.15" "--conf" "spark.app.name=Azure ML Experiment" "--conf" "spark.driver.memory=6g" "--conf" "spark.executor.memory=6g" "--conf" "spark.yarn.maxAppAttempts=1" "--driver-java-options" "-Dlog4j.configuration=file:./azureml-setup/log4j.properties" "--conf" "spark.eventLog.enabled=true" "--conf" "spark.eventLog.dir=./azureml-logs" spark_cache.py
 ---> Running in f2b34aa1271f
Exception in thread "main" java.lang.NoClassDefFoundError: org/spark_project/guava/cache/CacheLoader
	at org.apache.spark.deploy.SparkSubmitArguments.handleUnknown(SparkSubmitArguments.scala:460)
	at org.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:178)
	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:98)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.spark_project.guava.cache.CacheLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
The command '/bin/sh -c $SPARK_HOME/bin/spark-submit "--repositories" "https://mmlspark.azureedge.net/maven,https://azuremldownloads.blob.core.windows.net/repo5qh91kdjs6,https://azuremldownloads.blob.core.windows.net/repo5qh91kdjs6" "--packages" "com.microsoft.ml.spark:mmlspark_2.11:0.9.9,com.microsoft:dprep_2.11:0.15,com.microsoft.sqlserver:mssql-jdbc:6.2.1.jre8,com.microsoft:dprep_2.11:0.15" "--conf" "spark.app.name=Azure ML Experiment" "--conf" "spark.driver.memory=6g" "--conf" "spark.executor.memory=6g" "--conf" "spark.yarn.maxAppAttempts=1" "--driver-java-options" "-Dlog4j.configuration=file:./azureml-setup/log4j.properties" "--conf" "spark.eventLog.enabled=true" "--conf" "spark.eventLog.dir=./azureml-logs" spark_cache.py' returned a non-zero code: 1



Command '['docker', 'build', '-f', '/tmp/azureml_runs/PredictiveMaintenanceDL_1518454699779/azureml-setup/Dockerfile', '-t', 'azureml_34fb2d0449bd32d8c8fe56cc081f36e6', '.']' returned non-zero exit status 1
Uploading experiment status to history service.
Adding run profile attachment control_log
Logging experiment failure in history service.
Control script execution completed
```
